dados('1',['portugal','lisboa','fado','caixaalfama','40','25','verao','2','nao','32','urbano','europa','nao','9']).
dados('2',['portugal','elvas','eletronica','freedomdados','85','20','verao','5','sim','52','tradicional','europa','nao','2']).
dados('3',['portugal','portalegre','variado','dadosdocrato','30','8','verao','4','sim','19','rural','europa','sim','2']).
dados('4',['portugal','paredesdecoura','rock','paredesdecoura','90','40','verao','3','sim','65','fluvial','europa','sim','3']).
dados('5',['portugal','lisboa','variado','rockinriolisboa','18','60','verao','5','nao','39','urbano','europa','sim','5']).
dados('6',['portugal','vilanovadegaia','variado','meomaresvivas','60','35','verao','3','sim','47','urbano','europa','nao','4']).
dados('7',['portugal','oeiras','variado','nosalive','119','56','verao','3','sim','87','urbano','europa','sim','4']).
dados('8',['portugal','porto','variado','nosprimaverasoundporto','80','55','verao','2','nao','67','urbano','europa','nao','4']).
dados('9',['portugal','zambujeiradomar','variado','meosudoeste','95','48','verao','5','sim','71','praia','europa','sim','3']).
dados('10',['portugal','sesimbra','rock','superbocksuperrock','95','50','verao','3','sim','72','urbano','europa','nao','4']).
dados('11',['portugal','lisboa','variado','dadosdeinverno','30','25','inverno','2','nao','27','urbano','europa','nao','2']).
dados('12',['reinounido','glastonbury','variado','glastonburydados','0','0','verao','4','sim','0','urbano','europa','sim','3']).
dados('13',['alemanha','nuremberga','rock','rockamring','450','160','verao','3','sim','305','urbano','europa','nao','4']).
dados('14',['alemanha','nuremberga','rock','rockimpark','550','195','verao','3','sim','372','urbano','europa','nao','4']).
dados('15',['belgica','dessel','rock','graspopmetalmeeting','195','95','verao','3','sim','145','urbano','europa','nao','3']).
dados('16',['belgica','werchter','rock','rockwerchter','236','100','verao','4','sim','168','urbano','europa','nao','3']).
dados('17',['hungria','budapest','variado','szigetdados','249','59','verao','7','sim','154','urbano','europa','sim','5']).
dados('18',['reinounido','reading','variado','readingdados','220','70','verao','3','sim','145','rural','europa','nao','3']).
dados('19',['reinounido','leeds','variado','leedsdados','264','77','verao','3','sim','170','rural','europa','sim','3']).
dados('20',['alemanha','scheebel','rock','hurricanedados','180','75','verao','3','sim','127','rural','europa','nao','2']).
dados('21',['alemanha','schleswigholstein','rock','wackedopenair','200','80','verao','3','sim','140','rural','europa','nao','2']).
dados('22',['dinamarca','roskilde','variado','roskilde','300','130','verao','8','sim','215','rural','europa','nao','7']).
dados('23',['escocia','kinross','variado','tinthepark','200','80','verao','3','sim','140','rural','europa','sim','10']).
dados('24',['hungria','sopron','variado','voltdados','89','35','verao','4','sim','62','rural','europa','sim','10']).
dados('25',['polonia','kostrzynadodra','variado','woodstockdadospoland','0','0','verao','3','sim','0','rural','europa','sim','27']).
dados('26',['belgica','boom','eletronica','tomorrowland','650','235','verao','3','sim','442','rural','europa','sim','15']).
dados('27',['espanha','castello','eletronica','arenalsound','85','35','verao','4','sim','60','praia','europa','nao','4']).
dados('28',['holanda','haarlemmermeer','eletronica','mysterylanddados','0','0','verao','3','sim','0','rural','europa','sim','5']).
dados('29',['belgica','hasselt','variado','pukkelpop','200','99','verao','3','sim','149','rural','europa','sim','6']).
dados('30',['austria','nickelsdorf','rock','novarockdados','160','50','verao','4','sim','105','rural','europa','nao','3']).
dados('31',['holanda','landgraaf','rock','pinkpop','195','95','verao','3','sim','145','rural','europa','nao','3']).
dados('32',['holanda','biddinghuizen','variado','lowlands','175','70','verao','3','sim','122','rural','europa','sim','10']).
dados('33',['polonia','gdynia','variado','openerdados','100','55','verao','4','sim','77','rural','europa','sim','7']).
dados('34',['franca','carhaix-plouguer','variado','vieillescharruesdados','150','45','verao','4','sim','97','rural','europa','nao','4']).
dados('35',['espanha','barcelona','variado','sonar','180','45','verao','3','sim','112','urbano','europa','nao','5']).
dados('36',['suica','frauenfeld','hip-hop','openairfrauenfeld','180','90','verao','3','sim','135','rural','europa','nao','1']).
dados('37',['serbia','novisad','eletronica','exitdados','65','30','verao','4','47','fluvial','europa','nao','5']).
dados('38',['belgica','bruxelas','variado','couleurcafe','95','39','verao','3','sim','67','urbano','europa','sim','6']).
dados('39',['russia','moscovo','variado','afishapicnicdados','52','52','verao','1','nao','52','rural','europa','sim','3']).
dados('40',['franca','bourges','variado','pintempsdebourges','100','25','primavera','6','nao','62','urbano','europa','nao','13']).
dados('41',['franca','lyon','eletronica','nuitssonores','140','38','primavera','5','sim','89','urbano','europa','nao','4']).
dados('42',['alemanha','kastellaun','eletronica','natureonedados','200','79','verao','3','sim','139','rural','europa','sim','4']).
dados('43',['noruega','oslo','variado','oyadados','216','76','verao','5','146','fluvial','europa','sim','4']).
dados('44',['holanda','spaarnwoude','eletronica','dancevalley','65','65','verao','1','nao','65','rural','europa','sim','10']).
dados('45',['finlandia','seinjoki','variado','provinssirockdados','210','75','verao','4','sim','142','rural','europa','sim','2']).
dados('46',['espanha','bilbao','variado','bilbaubbklive','100','50','verao','3','sim','75','rural','europa','nao','2']).
dados('47',['irlanda','stradbally','eletronica','eletricpicnic','359','150','verao','3','sim','254','rural','europa','sim','4']).
dados('48',['suecia','slvesborg','rock','swedenrockdados','280','130','verao','4','sim','205','rural','europa','sim','3']).
dados('49',['suica','stgallen','variado','openairstgallen','0','0','verao','4','sim','0','rural','europa','nao','3']).
dados('50',['republicacheca','ostrava','variado','coloursofostrava','85','35','verao','4','sim','60','urbano','europa','nao','5']).
dados('51',['finlandia','ruissalo','rock','ruisrockdados','145','85','verao','3','sim','115','fluvial','europa','nao','2']).
dados('52',['letonia','salacgriva','variado','positivusdados','80','50','verao','3','sim','65','rural','europa','nao','3']).
dados('53',['franca','sermamagny','rock','eurockeenesdebelfort','115','44','verao','3','sim','79','fluvial','europa','nao','2']).
dados('54',['republicacheca','ceskybrod','rock','rockforpeople','58','25','verao','3','sim','41','rural','europa','nao','2']).
dados('55',['eslovaquia','trecin','variado','pohodadados','90','50','verao','3','sim','70','rural','europa','sim','5']).
dados('56',['holanda','weert','rock','bospop','100','65','verao','2','sim','82','rural','europa','sim','2']).
dados('57',['polonia','cracovia','variado','cokelivemusicdados','0','0','verao','2','nao','0','rural','europa','nao','1']).
dados('58',['eua','novaiorque','eletronica','eletricdaisycarnivalnewyork','207','107','primavera','2','nao','157','urbano','americadonorte','nao','7']).
dados('59',['noruega','tonsberg','variado','slottsfjelldados','210','103','verao','4','nao','156','rural','europa','nao','3']).
dados('60',['austria','viena','variado','urbanartformsdados','0','0','verao','1','nao','0','urbano','europa','nao','4']).
dados('61',['canada','montreal','variado','heavymontreal','186','100','verao','2','nao','143','urbano','americadonorte','nao','2']).
dados('62',['suecia','ostersund','variado','storsjoyran','120','75','verao','2','nao','97','rural','europa','nao','8']).
dados('63',['dinamarca','aarhus','variado','northside','187','120','primavera','3','nao','153','rural','europa','nao','4']).
dados('64',['eua','washington','variado','sasquatchdados1','316','85','primavera','4','sim','200','rural','americadonorte','nao','3']).
dados('65',['eua','oklahoma','rock','rockahoma','432','126','primavera','3','sim','279','rural','americadonorte','sim','3']).
dados('66',['luxemburgo','roeser','variado','rockafielddados','85','50','verao','2','sim','67','rural','europa','sim','4']).
dados('67',['eua','boston','variado','bostoncallingmusicdados','167','70','primavera','3','nao','118','urbano','americadonorte','nao','4']).
dados('68',['finlandia','joensuu','rock','ilosaarirockdados','151','79','verao','3','sim','115','fluvial','europa','sim','6']).
dados('69',['holanda','schijndel','pop','passpop','105','69','primavera','3','sim','87','urbano','europa','nao','9']).
dados('70',['dinamarca','skanderborg','variado','smukfest','295','90','verao','5','sim','192','rural','europa','sim','2']).
dados('71',['alemanha','rothenburgobdertauber','variado','taubertaldados','109','57','verao','4','sim','83','rural','europa','sim','1']).
dados('72',['espanha','murcia','variado','sos48dados','119','35','primavera','3','sim','77','urbano','europa','nao','3']).
dados('73',['canada','montreal','variado','osheaga','210','80','verao','3','nao','145','urbano','americadonorte','sim','3']).
dados('74',['hungria','zamrdi','variado','balatonsound','190','57','verao','5','nao','123','fluvial','europa','nao','7']).
dados('75',['irlanda','dublin','variado','longitudedados','159','64','verao','3','nao','111','urbano','europa','nao','2']).